# Generated by Django 6.0.1 on 2026-01-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prepmate", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachment",
            name="url",
        ),
        migrations.RemoveField(
            model_name="lessonplan",
            name="standard",
        ),
        migrations.AddField(
            model_name="lessonplan",
            name="standards",
            field=models.ManyToManyField(
                blank=True, related_name="lessons", to="prepmate.standard"
            ),
        ),
    ]
