# Generated by Django 6.0.1 on 2026-01-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prepmate", "0002_remove_attachment_url_remove_lessonplan_standard_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonplan",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
