# Generated by Django 6.0.1 on 2026-01-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prepmate", "0003_lessonplan_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonplan",
            name="grade",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="lessonplan",
            name="subject",
            field=models.TextField(blank=True, null=True),
        ),
    ]
