# Generated by Django 6.0.1 on 2026-01-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prepmate", "0004_lessonplan_grade_lessonplan_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="standard",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="standard",
            name="subject",
        ),
        migrations.AddField(
            model_name="standard",
            name="category_id",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="standard",
            name="category_name",
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name="standard",
            name="content_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="standard",
            name="grade_id",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="standard",
            name="grade_name",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="standard",
            name="item",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="standard",
            name="code",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="standard",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
