# Generated by Django 6.0.1 on 2026-01-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prepmate", "0005_remove_standard_grade_remove_standard_subject_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standard",
            name="code",
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
