# Generated by Django 6.0.1 on 2026-01-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prepmate", "0006_alter_standard_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonplan",
            name="notes",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
