# Generated by Django 6.0.1 on 2026-01-30 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prepmate", "0007_alter_lessonplan_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessonplan",
            name="date",
        ),
        migrations.CreateModel(
            name="LessonInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="prepmate.lessonplan",
                    ),
                ),
            ],
        ),
    ]
