# Generated by Django 6.0.2 on 2026-03-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepmate', '0008_remove_lessonplan_date_lessoninstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='grade_id',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='standard',
            name='item',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
