# Generated by Django 6.0.2 on 2026-03-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepmate', '0009_alter_standard_grade_id_alter_standard_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='category_id',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='standard',
            name='grade_id',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='standard',
            name='item',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
