# Generated by Django 6.0.2 on 2026-03-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepmate', '0010_alter_standard_category_id_alter_standard_grade_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='category_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
