# Generated by Django 6.0.2 on 2026-03-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepmate', '0011_alter_standard_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='category_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='standard',
            name='category_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standard',
            name='code',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='standard',
            name='content_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standard',
            name='grade_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
