# Generated by Django 6.0.2 on 2026-03-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepmate', '0013_alter_attachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
