# Generated by Django 6.0.2 on 2026-03-06 17:53

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prepmate', '0014_attachment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx'])]),
        ),
    ]
